package com.voidglass.launcher;
import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import java.util.*;
public class MainActivity extends Activity{
 V v; public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);v=new V();setContentView(v);} public void onResume(){super.onResume();if(v!=null){v.load();v.invalidate();}}
 class A{String n;Drawable i;Intent x;A(String n,Drawable i,Intent x){this.n=n;this.i=i;this.x=x;}}
 class V extends View{Paint p=new Paint(1);ArrayList<A>a=new ArrayList<>();android.content.SharedPreferences s;float down;int page=0,cols=5,rows=7;V(){super(MainActivity.this);s=getSharedPreferences("void",0);load();}void load(){a.clear();PackageManager m=getPackageManager();Intent q=new Intent(Intent.ACTION_MAIN);q.addCategory(Intent.CATEGORY_LAUNCHER);List<ResolveInfo> z=m.queryIntentActivities(q,0);Collections.sort(z,(u,w)->u.loadLabel(m).toString().compareToIgnoreCase(w.loadLabel(m).toString()));for(ResolveInfo r:z){if(r.activityInfo.packageName.equals(getPackageName()))continue;Intent x=new Intent(Intent.ACTION_MAIN);x.addCategory(Intent.CATEGORY_LAUNCHER);x.setClassName(r.activityInfo.packageName,r.activityInfo.name);a.add(new A(r.loadLabel(m).toString(),r.loadIcon(m),x));}}
 protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setShader(new LinearGradient(0,0,w,h,new int[]{0xff03050b,0xff101a2e,0xff05070d},null,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(0x2870dfff);p.setMaskFilter(new BlurMaskFilter(75,BlurMaskFilter.Blur.NORMAL));c.drawCircle(w*.82f,h*.18f,130,p);p.setMaskFilter(null);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(20);c.drawText(time(),20,35,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(11);p.setColor(0xccffffff);c.drawText("Void Glass",20,54,p);glass(c,15,67,w-15,111,25);p.setTextSize(12);c.drawText("⌕  Search apps",31,95,p);float cw=w/(float)cols,top=127,ch=68;int size=(int)(46*s.getInt("icon",76)/100f);int start=page*cols*rows;for(int i=0;i<cols*rows;i++){int k=start+i;if(k>=a.size())break;int co=i%cols,ro=i/cols;float x=cw*co+cw/2,y=top+ro*ch+27;icon(c,a.get(k).i,x,y,size);if(!s.getBoolean("hideLabels",false)){p.setTextAlign(Paint.Align.CENTER);p.setTextSize(9);p.setColor(0xddffffff);String n=a.get(k).n;if(n.length()>10)n=n.substring(0,9)+"…";c.drawText(n,x,y+size/2+14,p);p.setTextAlign(Paint.Align.LEFT);}}int pages=Math.max(1,(a.size()+cols*rows-1)/(cols*rows));for(int i=0;i<pages;i++){p.setColor(i==page?Color.WHITE:0x55ffffff);c.drawCircle(w/2f+(i-(pages-1)/2f)*11,h-101,3,p);}glass(c,14,h-83,w-14,h-14,29);int d=Math.min(5,a.size());for(int i=0;i<d;i++)icon(c,a.get(i).i,14+(w-28)*(i+.5f)/d,h-48,37);}
 String time(){Calendar z=Calendar.getInstance();return String.format(Locale.getDefault(),"%02d:%02d",z.get(Calendar.HOUR_OF_DAY),z.get(Calendar.MINUTE));}void glass(Canvas c,float l,float t,float r,float b,float rad){p.setColor(Color.argb(s.getInt("trans",72),255,255,255));c.drawRoundRect(l,t,r,b,rad,rad,p);p.setStyle(Paint.Style.STROKE);p.setColor(0x4affffff);p.setStrokeWidth(1);c.drawRoundRect(l,t,r,b,rad,rad,p);p.setStyle(Paint.Style.FILL);}void icon(Canvas c,Drawable d,float x,float y,int z){float l=x-z/2f,t=y-z/2f;p.setColor(0x35ffffff);c.drawRoundRect(l,t,l+z,t+z,14,14,p);d.setBounds((int)l+3,(int)t+3,(int)l+z-3,(int)t+z-3);d.draw(c);}public boolean onTouchEvent(MotionEvent e){if(e.getAction()==0){down=e.getX();return true;}if(e.getAction()==1){float dx=e.getX()-down;if(Math.abs(dx)>70){int pages=Math.max(1,(a.size()+cols*rows-1)/(cols*rows));if(dx<0&&page<pages-1)page++;if(dx>0&&page>0)page--;invalidate();return true;}if(e.getY()<115&&e.getY()>60){startActivity(new Intent(MainActivity.this,SettingsActivity.class));return true;}int w=getWidth(),h=getHeight();if(e.getY()>127&&e.getY()<h-90){int co=(int)(e.getX()/(w/(float)cols)),ro=(int)((e.getY()-127)/68),k=page*cols*rows+ro*cols+co;if(co>=0&&co<cols&&ro>=0&&ro<rows&&k<a.size()){startActivity(a.get(k).x);if(s.getBoolean("haptic",true))performHapticFeedback(HapticFeedbackConstants.VIRTUAL_KEY);}}return true;}return true;}}
}
